### ISSUE TITLE
Documented way to create a PDF::Table object gives errors

### ISSUE THREAD

**Issue by philgoetz** [kamenov/PDF-Table#17]
$ perl -e 'use PDF::Table; $table = new PDF::Table; use Data::Dumper; $f=Dumper($table); print "$f"'
Warning: Page must be a PDF::API2::Page object but it seems to be:
 at -e line 1.
Error: Cannot set page from passed PDF object either as it is invalid!
 at -e line 1.
$VAR1 = bless( {
                 'pdf' => undef,
                 'font_size' => 12
               }, 'PDF::Table' );

cpan> i PDF::Table
Module id = PDF::Table
    CPAN_USERID  OMEGA (Desislav Kamenov <omega@cpan.org>)
    CPAN_VERSION 0.009009
    CPAN_FILE    O/OM/OMEGA/PDF-Table-0.9.9.tar.gz
    UPLOAD_DATE  2015-05-28
    MANPAGE      PDF::Table - A utility class for building table layouts in a PDF::API2 object.
    INST_FILE    /usr/lib/perl5/site_perl/5.14/PDF/Table.pm
    INST_VERSION 0.9.9

The code says that the parameters $pdf, $page, $data, and %options are mandatory.
$page is in fact not mandatory, but without $pdf it will give an error message. $data and %options are ignored.

**Comment by kamenov** [comment]
I'm on it.

**Comment by azawawi** [comment]
Any update on this one? I tried using your great module but it failed with that error.

**Comment by kamenov** [comment]
I totally forgot about this one :( I'm sorry about that. Will spend time on it this week.
Contributions will be highly appreciated.

**Comment by azawawi** [comment]
And here is the fix. Please let me know if you need any changes :+1:

**Comment by philgoetz** [comment]
Thanks!
