### ISSUE TITLE
Greediness modifier warning with Perl 5.20.1

### ISSUE THREAD

**Issue by mpitzl** [kamenov/PDF-Table#20]
Hi,

The regex in this line causes a Perl warning about the useless '?' modifier:
```perl
                $data->[$row_idx][$column_idx] =~ s#(\S{$max_word_len}?)(?=\S)#$1 #g;
```

-- Matthias

**Comment by kamenov** [comment]
Hi, thanks for reporting.
It has been fixed with pull request #18 and included in version 0.9.10
