### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [kamenov/PDF-Table#24]
Your distribution (OMEGA/PDF-Table-0.9.10.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=OMEGA and contact me.

**Comment by kamenov** [comment]
HI @chorny,
Thanks for reporting that issue. It has already been fixed with commit a73e67f but it has not been included into a new version.

**Comment by kamenov** [comment]
Included in version 0.9.11
