### ISSUE TITLE
font_color_odd is not a valid setting key

### ISSUE THREAD

**Issue by melqu1ades** [kamenov/PDF-Table#33]
In sub _table_ it has been added a check on valid keys but it misses 'font_color_odd' key. This check was not present in 0.9.5.

 my %valid_settings_key = ( 
290 	x                     => 1, 
291         w                     => 1, 
292         start_y               => 1, 
293         start_h               => 1, 
294         next_y                => 1, 
295         next_h                => 1, 
296         lead                  => 1, 
297         padding               => 1, 
298         padding_right         => 1, 
299         padding_left          => 1, 
300         padding_top           => 1, 
301         padding_bottom        => 1, 
302         background_color      => 1, 
303         background_color_odd  => 1, 
304         background_color_even => 1, 
305         border                => 1, 
306         border_color          => 1, 
307         horizontal_borders    => 1, 
308         vertical_borders      => 1, 
309         font                  => 1, 
310         font_size             => 1, 
**311         font_color            => 1, 
312         font_color_even       => 1,** 
313         background_color_odd  => 1, 
314         background_color_even => 1, 
315         row_height            => 1, 
316         new_page_func         => 1, 
317         header_props          => 1, 
318         column_props          => 1, 
319         cell_props            => 1, 
320         max_word_length       => 1, 
321         cell_render_hook      => 1, 
322     ); 
323     foreach my $key (keys %arg) 
324     { 
325         # Provide backward compatibility 
326         $arg{$key} = delete $arg{"-$key"} if $key =~ s/^-//; 
327 
 
328         croak "Error: Invalid setting key '$key' received." 
329             unless exists $valid_settings_key{$key}; 
330     }

**Comment by kamenov** [comment]
Uploaded version 0.9.13 to CPAN
