### ISSUE TITLE
Question: How to have table render over watermark image?

### ISSUE THREAD

**Issue by djzort** [kamenov/PDF-Table#38]
Hi there,
I am trying to render a table that goes over the top of a watermark image. however PDF::Table is smart and skips to the next page.

Is there a way to make pdf::table render over other objects? I cant read anything in the documetnation.

Thanks

**Comment by kamenov** [comment]
Hi,

How do you place the watermark image?
In theory if you set explicitly the starting coordinates of the table  pdf::table should place it on top of whatever is already there.

**Comment by djzort** [comment]
its just a misunderstanding of start_h parameter. sorry to waste your time

**Comment by PhilterPaper** [comment]
Just a reminder that `start_h` (now `h`) and `next_h` are the _maximum_ height of the table on a page, not the _required_ height. Likewise, `start_y` (now `y`) and `next_y` are the starting position (upper left) of the table on a page, regardless of anything that's already been put down on that page.
