### ISSUE TITLE
Underline text?

### ISSUE THREAD

**Issue by djzort** [kamenov/PDF-Table#39]
Is it possible to underline text?

Its available in PDF::API2 via http://search.cpan.org/~ssimms/PDF-API2-2.033/lib/PDF/API2/Content.pm#Text-Showing

But I cant see an obvious way to pass it in, and reading through the code of PDF::Table I cant see  less obvious way either?

**Comment by kamenov** [comment]
I don’t think there is such a feature in PDF::Table at the moment. If you open PR with the required changes I’d be happy to merge and release it as soon as possible.

**Comment by djzort** [comment]
PR https://github.com/kamenov/PDF-Table/pull/40

**Comment by kamenov** [comment]
Released version 0.10.0 to CPAN
http://search.cpan.org/~omega/PDF-Table-0.10.0/lib/PDF/Table.pm
