### ISSUE TITLE
Version 0.9.7 x 0.9.5

### ISSUE THREAD

**Issue by acar11** [kamenov/PDF-Table#8]
In the version 0.9.5 of Table.pm I couldn't align data inside of the table cells or control the data alignment inside of the table cells. But using code like this:
$cell_props->[51]->[10] = {
                                    font => $font{'Helvetica'}{'Bold'},
                                    font_size      => 8,
                                    background_color => '#BFBFBF', 
                                    font_color       => '#FF0000', 
                                    justify => "center",
                                };
I can. But the new version 0.9.7 is placing these settings ( I am creating  multiple pages documents) out  of its place after  the first page. Any ideas what was dramatically changed that is causing this? I can send you some sample code to illustrate what I am trying to explain here.

**Comment by kamenov** [comment]
Closing due to timeout. If problem still exists, please reopen.
